apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 2
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-nginx-app
        image: pilsu/hairpin-react:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-react
spec:
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
